### PR TITLE
Add justpass.me

### PR DESCRIPTION
**Pull request by mkalioby**
-   **Domain Name**:  justpass.me
-   **Purpose**: JustPass.me provides a Passkeys-as-a-service for web apps and mobile apps through OpenID Connect Protocol and it supports Firebase.
-   **Relevance**: 
Supports Passkey

### CODE REVIEW

**Comment by mkalioby** [comment]
Done

**Comment by mkalioby** [comment]
When will it available on the site?

**Comment by Mikescops** [comment]
> When will it available on the site?

@mkalioby once the PR is merged, the CI does the deployment in a couple of minutes 

but in your case, `https://justpass.me` is not resolvable, it sounds like the real domain you use is `www.justpass.me`

maybe you want to fix that by adding a redirection

on our end we can also check `www.` as a fallback

**Comment by Mikescops** [comment]
I could fix it with #22 
image

**Comment by mkalioby** [comment]
How, it is resolvable as shown below

**Comment by mkalioby** [comment]
Thx

**Comment by Mikescops** [comment]
@mkalioby look: 

image


but www.justpass.me is resolvable

**Pull request merged**
